import { SpeakUpShell } from "@/components/SpeakUpShell";
import { WaveVisual } from "@/components/WaveVisual";
import { Button } from "@/components/ui/button";
import { ArrowRight, BarChart3, BrainCircuit, CircleDotDashed, Clock3, MessageSquareText, Mic, Sparkles, Timer, UsersRound } from "lucide-react";
import { Link } from "wouter";

const practiceTypes = [
  { title: "JAM Practice", eyebrow: "01 minute • voice", body: "Think fast and make a clear point before the timer ends.", icon: Timer, href: "/jam", tone: "warm" },
  { title: "Group Discussion", eyebrow: "05 AI perspectives", body: "Open, counter, and find your voice in a shared discussion.", icon: UsersRound, href: "/discussion", tone: "purple" },
  { title: "Interview Practice", eyebrow: "HR • behavioral • technical", body: "Answer one question at a time and sharpen your narrative.", icon: MessageSquareText, href: "/interview", tone: "blue" },
  { title: "Random Challenge", eyebrow: "No overthinking", body: "Draw a topic and start speaking right now.", icon: Sparkles, href: "/topics", tone: "slate" },
];

export default function Dashboard() {
  return <SpeakUpShell><main className="app-container pb-16 pt-10 md:pt-14"><section className="dashboard-hero overflow-hidden rounded-[30px] border border-border bg-card p-6 md:p-10"><div className="grid items-center gap-8 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Today’s practice</p><h1 className="mt-5 max-w-2xl text-4xl font-semibold tracking-[-.055em] md:text-5xl">Give your next answer a <span className="font-serif italic text-[var(--accent)]">better shape.</span></h1><p className="mt-5 max-w-xl leading-7 text-muted-foreground">Choose a format, get a topic, and begin in seconds. Every practice starts with a clean slate.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/jam"><Button className="rounded-full px-5">Start JAM session <ArrowRight className="ml-1 h-4 w-4" /></Button></Link><Link href="/topics"><Button variant="outline" className="rounded-full bg-background">Draw a random topic</Button></Link></div></div><div className="relative min-h-52 rounded-3xl border border-border/70 bg-background/70 px-6 py-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[.16em] text-muted-foreground">Practice pulse</span><CircleDotDashed className="h-5 w-5 text-[var(--accent)]" /></div><WaveVisual className="h-32" /><div className="flex items-end justify-between"><div><p className="text-xs text-muted-foreground">One focused round</p><p className="mt-1 font-semibold">is enough to build momentum.</p></div><span className="text-3xl font-serif italic text-[var(--accent)]">01:00</span></div></div></div></section>
  <section className="mt-12"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Quick start</p><h2 className="mt-3 text-2xl font-semibold tracking-[-.04em]">What do you want to practise?</h2></div><Link href="/topics" className="hidden text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground sm:block">Browse topics <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{practiceTypes.map(item => <Link key={item.title} href={item.href} className={`practice-card ${item.tone}`}><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-background/80 shadow-sm"><item.icon className="h-5 w-5" /></span><ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></div><p className="mt-9 text-[11px] font-semibold uppercase tracking-[.14em] text-muted-foreground">{item.eyebrow}</p><h3 className="mt-2 text-xl font-semibold tracking-[-.035em]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.body}</p></Link>)}</div></section>
  <section className="mt-12 grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl border border-border bg-card p-6 md:p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">This week</p><p className="mt-1 text-sm text-muted-foreground">Your practice is ready when you are.</p></div><BarChart3 className="h-5 w-5 text-[var(--accent)]" /></div><div className="mt-8 grid grid-cols-2 gap-y-7 sm:grid-cols-4"><div><p className="text-2xl font-semibold tracking-[-.05em]">—</p><p className="mt-1 text-xs text-muted-foreground">Sessions</p></div><div><p className="text-2xl font-semibold tracking-[-.05em]">—</p><p className="mt-1 text-xs text-muted-foreground">Avg. score</p></div><div><p className="text-2xl font-semibold tracking-[-.05em]">0 min</p><p className="mt-1 text-xs text-muted-foreground">Speaking time</p></div><div><p className="text-2xl font-semibold tracking-[-.05em]">New</p><p className="mt-1 text-xs text-muted-foreground">Your streak</p></div></div></div><div className="rounded-3xl bg-slate-950 p-6 text-white dark:bg-white dark:text-slate-950"><div className="flex items-center justify-between"><span className="text-sm font-medium opacity-70">Next best action</span><BrainCircuit className="h-5 w-5 text-[var(--accent)]" /></div><p className="mt-8 max-w-xs text-2xl font-semibold tracking-[-.04em]">Try one untimed topic to find your natural pace.</p><Link href="/topics"><Button className="mt-7 rounded-full bg-[var(--accent)] text-white hover:bg-[var(--accent)]/90">Generate topic <Mic className="ml-1 h-4 w-4" /></Button></Link></div></section></main></SpeakUpShell>;
}
