import { BrandMark } from "@/components/BrandMark";
import { SpeakUpShell } from "@/components/SpeakUpShell";
import { WaveVisual } from "@/components/WaveVisual";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, BadgeCheck, BarChart3, BrainCircuit, Check, ChevronRight, CirclePlay, MessageSquareText, Mic, Sparkles, Timer, TrendingUp, UsersRound } from "lucide-react";
import { Link } from "wouter";

const featureCards = [
  { icon: Timer, label: "JAM practice", title: "Think on your feet.", text: "A focused 60-second speaking loop built around topics that matter in real interviews.", href: "/jam", accent: "coral" },
  { icon: UsersRound, label: "Group discussion", title: "Join the conversation.", text: "Meet five distinct AI perspectives, practise responding, and learn to make room for your point.", href: "/discussion", accent: "violet" },
  { icon: MessageSquareText, label: "AI interview", title: "Sound like yourself.", text: "Answer questions one at a time, review your delivery, and build a stronger interview narrative.", href: "/interview", accent: "blue" },
];

const steps = [
  ["01", "Pick a practice", "Choose a JAM round, a discussion, or an interview question."],
  ["02", "Speak in the moment", "Use your microphone and focus on making your next point."],
  ["03", "See the pattern", "Review a structured score, transcript, and practical next step."],
];

export default function Landing() {
  return <SpeakUpShell publicOnly>
    <main>
      <section className="relative isolate overflow-hidden">
        <div className="hero-grid pointer-events-none absolute inset-0 -z-10 opacity-80" />
        <div className="app-container grid min-h-[680px] items-center gap-14 pb-20 pt-20 lg:grid-cols-[1.05fr_.95fr] lg:pb-28 lg:pt-28">
          <div className="max-w-2xl">
            <div className="eyebrow mb-6"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Communication practice, made personal</div>
            <h1 className="display-title text-balance">Your voice is your <span className="font-serif italic text-[var(--accent)]">interview</span> advantage.</h1>
            <p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Practise JAM rounds, group discussions, and interviews through immersive voice sessions with feedback you can use on your very next attempt.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Button onClick={() => startLogin()} size="lg" className="h-12 rounded-full px-6 text-[15px]">Start practicing <ArrowRight className="ml-1 h-4 w-4" /></Button><Link href="/app"><Button variant="outline" size="lg" className="h-12 rounded-full border-border bg-background px-6 text-[15px]">Explore the workspace <CirclePlay className="ml-1 h-4 w-4" /></Button></Link></div>
            <div className="mt-10 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[var(--accent)]" /> No rehearsal scripts</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[var(--accent)]" /> Your browser, your voice</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-[500px]">
            <div className="absolute -inset-10 -z-10 rounded-full bg-[radial-gradient(circle,rgba(255,108,88,.17),transparent_65%)] blur-2xl dark:bg-[radial-gradient(circle,rgba(255,123,101,.13),transparent_65%)]" />
            <div className="hero-recorder-card rounded-[30px] border border-white/70 bg-white/75 p-5 shadow-[0_30px_80px_rgba(28,35,53,.13)] backdrop-blur-xl dark:border-white/10 dark:bg-slate-900/75">
              <div className="flex items-center justify-between border-b border-border/60 pb-4"><div className="flex items-center gap-2 text-xs font-medium text-muted-foreground"><span className="h-2 w-2 rounded-full bg-[var(--accent)] animate-pulse" /> Live practice</div><span className="rounded-full bg-[var(--soft-accent)] px-3 py-1 text-xs font-semibold text-[var(--accent-ink)]">JAM · 60 seconds</span></div>
              <div className="px-3 pt-9 text-center"><p className="text-sm font-medium text-muted-foreground">Your topic is</p><h2 className="mt-3 text-[27px] font-semibold leading-tight tracking-[-.04em]">Is social media making students more productive?</h2></div>
              <div className="relative mx-auto mt-8 grid h-64 w-64 place-items-center rounded-full border border-slate-200/80 bg-[radial-gradient(circle_at_50%_35%,#fff,rgba(247,243,239,.7))] dark:border-white/10 dark:bg-[radial-gradient(circle_at_50%_35%,#1d2939,#111827)]"><div className="absolute inset-3 rounded-full border-[9px] border-[var(--soft-accent)] border-t-[var(--accent)]" /><div className="z-10 grid h-20 w-20 place-items-center rounded-full bg-slate-950 text-white shadow-xl dark:bg-white dark:text-slate-950"><Mic className="h-7 w-7" /></div><span className="absolute bottom-11 z-10 text-xs font-bold tracking-[.22em] text-muted-foreground">READY</span></div>
              <WaveVisual className="h-20 opacity-75" />
              <div className="flex items-center justify-between rounded-2xl bg-slate-950 px-5 py-4 text-white dark:bg-white dark:text-slate-950"><div><p className="text-xs opacity-60">Focus score</p><p className="mt-1 text-lg font-semibold">Building momentum</p></div><Sparkles className="h-5 w-5 text-[var(--accent)]" /></div>
            </div>
            <div className="absolute -bottom-5 -left-4 rounded-2xl border border-border/70 bg-background/90 px-4 py-3 shadow-lg backdrop-blur-xl"><p className="text-xs text-muted-foreground">One focused round</p><p className="mt-0.5 font-serif text-xl italic text-[var(--accent)]">starts a clearer answer.</p></div>
          </div>
        </div>
      </section>

      <section id="how-it-works" className="border-y border-border/70 bg-muted/35 py-24"><div className="app-container"><div className="grid gap-8 md:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> A tight feedback loop</p><h2 className="section-title mt-5">Practise the part that matters: <span className="font-serif italic">your delivery.</span></h2></div><div className="grid gap-3">{steps.map(([number, title, body]) => <div key={number} className="step-row"><span className="font-serif text-xl italic text-[var(--accent)]">{number}</span><div><h3 className="font-semibold tracking-[-.02em]">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{body}</p></div></div>)}</div></div></div></section>

      <section className="app-container py-28"><div className="max-w-2xl"><p className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Purpose-built practice</p><h2 className="section-title mt-5">A format for every high-stakes <span className="font-serif italic">conversation.</span></h2></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{featureCards.map(feature => <Link key={feature.title} href={feature.href} className="feature-card group"><div className={`feature-icon ${feature.accent}`}><feature.icon className="h-5 w-5" /></div><p className="mt-8 text-xs font-semibold uppercase tracking-[.16em] text-muted-foreground">{feature.label}</p><h3 className="mt-3 text-2xl font-semibold tracking-[-.04em]">{feature.title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">{feature.text}</p><span className="mt-8 inline-flex items-center gap-1.5 text-sm font-semibold">Explore <ChevronRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div></section>

      <section className="app-container pb-28"><div className="rounded-[32px] bg-slate-950 px-7 py-12 text-white shadow-[0_30px_70px_rgba(13,22,38,.2)] md:px-14 md:py-16"><div className="grid items-center gap-10 lg:grid-cols-[1fr_.75fr]"><div><p className="eyebrow text-slate-400"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Voice analysis</p><h2 className="mt-5 max-w-xl text-4xl font-semibold tracking-[-.055em] md:text-5xl">Useful feedback is specific, not generic.</h2><p className="mt-5 max-w-lg leading-7 text-slate-400">See your pace, clarity, confidence, structure, and filler words together. Then make one deliberate improvement at a time.</p><Link href="/app"><Button className="mt-8 rounded-full bg-white px-6 text-slate-950 hover:bg-white/90">See practice workspace <ArrowRight className="ml-1 h-4 w-4" /></Button></Link></div><div className="grid gap-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-400">Overall clarity</span><span className="text-lg font-semibold">Your score</span></div><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full w-[70%] rounded-full bg-[var(--accent)]" /></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><BrainCircuit className="h-5 w-5 text-[var(--accent)]" /><p className="mt-5 text-sm text-slate-400">Stronger structure</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><BarChart3 className="h-5 w-5 text-[var(--accent)]" /><p className="mt-5 text-sm text-slate-400">Progress you can see</p></div></div></div></div></div></section>
      <section className="app-container pb-28"><div className="grid gap-10 rounded-[32px] border border-border bg-card p-7 md:grid-cols-[.9fr_1.1fr] md:p-12"><div><p className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Progress tracking</p><h2 className="section-title mt-5">Make improvement <span className="font-serif italic">visible.</span></h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">Your dashboard turns completed sessions into an honest record of speaking time, score trends, confidence, and earned milestones.</p><Link href="/progress"><Button variant="outline" className="mt-7 rounded-full bg-background">Explore progress <ArrowRight className="ml-1 h-4 w-4" /></Button></Link></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted/60 p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Practice record</p><p className="mt-7 text-3xl font-semibold tracking-[-.06em]">Your data</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Session scores, speaking time, and trends that belong to you.</p></div><div className="rounded-2xl bg-[var(--soft-accent)] p-5"><TrendingUp className="h-5 w-5 text-[var(--accent-ink)]" /><p className="mt-7 text-lg font-semibold tracking-[-.04em] text-[var(--accent-ink)]">Weekly review</p><p className="mt-2 text-sm leading-6 text-[var(--accent-ink)]/75">Spot the difference one session at a time.</p></div><div className="col-span-2 rounded-2xl bg-slate-950 p-5 text-white dark:bg-white dark:text-slate-950"><div className="flex items-center justify-between"><span className="text-sm font-medium opacity-60">Achievements</span><BadgeCheck className="h-5 w-5 text-[var(--accent)]" /></div><p className="mt-6 text-xl font-semibold tracking-[-.04em]">Earn every badge through your own practice.</p></div></div></div></section>

      <section className="border-y border-border/70 bg-muted/35 py-24"><div className="app-container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Testimonials</p><h2 className="section-title mt-5">Built on practice, not performance theatre.</h2></div><div className="rounded-3xl border border-border bg-background p-7 md:p-10"><BadgeCheck className="h-7 w-7 text-[var(--accent)]" /><h3 className="mt-6 text-2xl font-semibold tracking-[-.04em]">Verified learner stories belong here.</h3><p className="mt-3 max-w-xl leading-7 text-muted-foreground">SpeakUp does not invent feedback or testimonials. This space is reserved for verified learner stories when they are available.</p></div></div></section>
      <section className="app-container py-28 text-center"><p className="eyebrow justify-center"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Your next attempt starts here</p><h2 className="section-title mx-auto mt-5 max-w-3xl">Speak clearly. Think quickly. <span className="font-serif italic">Interview confidently.</span></h2><Button onClick={() => startLogin()} size="lg" className="mt-8 rounded-full px-7">Start practicing <ArrowRight className="ml-1 h-4 w-4" /></Button></section>
    </main>
    <footer className="border-t border-border py-7"><div className="app-container flex flex-wrap items-center justify-between gap-3 text-sm text-muted-foreground"><BrandMark compact /><span>Practice your point. Own your voice.</span></div></footer>
  </SpeakUpShell>;
}
