import type { InterviewCategory } from "@shared/practice";

const questions: Record<InterviewCategory, string[]> = {
  HR: [
    "Tell me about yourself in a way that connects your background to this role.", "Why does this role interest you now?", "What strengths would your manager rely on most?", "What skill are you deliberately improving, and how are you measuring progress?", "What kind of environment helps you do your best work?", "What would make you choose one offer over another?", "Describe a career decision that was difficult but valuable.", "How do you handle feedback you disagree with?", "What does meaningful work look like to you?", "How would you explain a career gap or a change in direction?",
  ],
  Behavioral: [
    "Tell me about a time you received difficult feedback and changed your approach.", "Describe a difficult team situation and what you did to improve it.", "Tell me about a leadership experience when you did not have formal authority.", "Describe a project that did not go as planned. How did you respond?", "Tell me about a time you had to make a decision with incomplete information.", "Describe a disagreement with a stakeholder and how you resolved it.", "Give an example of when you had to prioritise competing deadlines.", "Tell me about a time you simplified a complex problem for someone else.", "Describe a risk you identified before it became a larger issue.", "Tell me about a time you helped a teammate succeed.",
  ],
  Technical: [
    "Explain a project you are proud of using the problem, your approach, trade-offs, and outcome.", "How would you approach an AI or data problem with incomplete or biased data?", "Describe a database design decision you made and the trade-off behind it.", "What programming practice has most improved the reliability of your work?", "How would you debug an intermittent production issue?", "How would you design an API that must remain backwards compatible?", "How would you evaluate whether a new AI feature is useful and safe for users?", "Describe how you would improve a slow web application without guessing.", "How would you approach a security review for a feature that handles personal data?", "How would you decide whether to build, buy, or integrate a third-party tool?",
  ],
  Product: ["How would you identify the most important user problem to solve next?", "How would you evaluate whether a product experiment succeeded?", "Describe a product trade-off between speed, quality, and scope.", "How would you respond when user feedback conflicts with business goals?", "How would you decide which metric matters most for a new feature?", "How would you explain a product decision to a non-technical stakeholder?", "How would you improve an onboarding experience with limited research time?", "When should a product team say no to a popular request?", "How would you prioritise a backlog after a sudden customer escalation?", "Describe a product you admire and one improvement you would make."],
  Leadership: ["How do you create alignment when a team has competing priorities?", "Describe a time you influenced a decision without formal authority.", "How do you build trust with a new team?", "What does accountability look like when a project misses its goal?", "How would you handle a high-performing teammate whose behaviour hurts collaboration?", "How do you communicate uncertainty without creating panic?", "How would you approach a difficult decision that affects your team?", "How do you help others grow while meeting urgent delivery goals?", "Describe a leadership lesson you learned the hard way.", "What would your first 90 days as a team lead look like?"],
  Situational: ["A key stakeholder changes priorities one week before launch. What do you do?", "You discover an important mistake after sharing a recommendation. How do you respond?", "Two teammates strongly disagree on an approach. How would you move forward?", "You have three urgent tasks and only time to complete one well. How do you decide?", "A customer asks for a commitment you cannot responsibly make. What do you say?", "You are asked to use data you do not fully trust. What is your approach?", "Your project is on track technically but users are not adopting it. What would you investigate?", "A new team member is struggling but deadlines are tight. How would you support them?", "You are given an ambiguous goal with no success metric. What is your first step?", "A senior leader challenges your recommendation in a meeting. How do you respond?"],
};

export function getInterviewQuestion(category: InterviewCategory, index: number) {
  const list = questions[category];
  return { question: list[index % list.length]!, total: list.length, index: index % list.length };
}
