import type { Difficulty, Topic, TopicCategory, TopicSource } from "@shared/practice";

type Seed = Omit<Topic, "id" | "source" | "sourceLabel">;
const make = (id: string, text: string, category: Exclude<TopicCategory, "Random">, difficulty: Difficulty, suitableDurations: (30 | 60 | 90)[]): Topic => ({ id, text, category, difficulty, suitableDurations, source: "curated", sourceLabel: "Curated practice prompt" });

export const topicCatalogue: Topic[] = [
  make("edu-ai-literacy", "Should AI literacy be a core subject in every school?", "Education", "Medium", [30, 60, 90]), make("edu-assessment", "Should schools move away from high-stakes exams?", "Education", "Hard", [60, 90]), make("edu-skills", "How should colleges balance degrees with job-ready skills?", "Education", "Medium", [30, 60]), make("edu-mental", "What responsibility do universities have for student wellbeing?", "Education", "Medium", [60, 90]), make("edu-micro", "Can short courses compete with traditional qualifications?", "Education", "Easy", [30, 60]), make("edu-language", "Should multilingual learning be encouraged in classrooms?", "Education", "Easy", [30, 60]),
  make("tech-agents", "How should workplaces adopt AI agents responsibly?", "Technology", "Hard", [60, 90]), make("tech-privacy", "Should personal data be treated as private property?", "Technology", "Hard", [60, 90]), make("tech-open", "Should governments prefer open-source software for public services?", "Technology", "Medium", [30, 60]), make("tech-deepfake", "How should platforms respond to convincing deepfakes?", "Technology", "Hard", [60, 90]), make("tech-access", "Does technology reduce or widen inequality?", "Technology", "Medium", [30, 60]), make("tech-automation", "Which human skills become more valuable as automation grows?", "Technology", "Easy", [30, 60]),
  make("soc-attention", "Is the attention economy harming meaningful conversation?", "Society", "Medium", [30, 60]), make("soc-community", "How can cities build stronger local communities?", "Society", "Easy", [30, 60]), make("soc-remote", "Has remote work changed how people belong at work?", "Society", "Medium", [60, 90]), make("soc-age", "How should societies prepare for longer working lives?", "Society", "Hard", [60, 90]), make("soc-trust", "What makes people trust an institution?", "Society", "Easy", [30, 60]), make("soc-public", "When does public safety justify convenience trade-offs?", "Society", "Hard", [60, 90]),
  make("career-first", "What should a graduate prioritise in a first job?", "Career", "Easy", [30, 60]), make("career-feedback", "How should an employee ask for actionable feedback?", "Career", "Easy", [30, 60]), make("career-leadership", "What does good leadership look like in uncertain times?", "Career", "Medium", [60, 90]), make("career-switch", "How should professionals approach a career pivot?", "Career", "Medium", [30, 60]), make("career-hybrid", "What makes hybrid work successful?", "Career", "Medium", [60, 90]), make("career-network", "Is networking more about generosity than self-promotion?", "Career", "Easy", [30, 60]),
  make("business-pricing", "Should companies prioritise growth or sustainable profitability?", "Business", "Hard", [60, 90]), make("business-startup", "What makes a startup idea defensible?", "Business", "Medium", [30, 60]), make("business-cx", "How should companies use customer feedback without chasing every request?", "Business", "Hard", [60, 90]), make("business-local", "Can local businesses compete effectively with large platforms?", "Business", "Medium", [30, 60]), make("business-fourday", "Would a four-day workweek make businesses stronger?", "Business", "Hard", [60, 90]), make("business-ethics", "When should a company turn down a profitable opportunity?", "Business", "Hard", [60, 90]),
  make("current-energy", "How should countries balance energy security with clean-energy transition?", "Current Affairs", "Hard", [60, 90]), make("current-mobility", "How should cities redesign transport for growing populations?", "Current Affairs", "Medium", [60, 90]), make("current-health", "What should responsible innovation in public health look like?", "Current Affairs", "Hard", [60, 90]), make("current-food", "How can food systems become more resilient?", "Current Affairs", "Medium", [30, 60]), make("current-space", "What rules should govern commercial activity in space?", "Current Affairs", "Hard", [60, 90]), make("current-water", "How should communities respond to water stress?", "Current Affairs", "Medium", [60, 90]),
  make("culture-creative", "How can technology support creative work without replacing creative judgment?", "Culture", "Medium", [30, 60]), make("culture-heritage", "How should communities preserve culture while welcoming change?", "Culture", "Medium", [60, 90]), make("culture-media", "What responsibility do creators have when shaping public conversation?", "Culture", "Hard", [60, 90]), make("sustainability-circular", "How can businesses move from waste reduction to circular design?", "Sustainability", "Medium", [60, 90]), make("sustainability-climate", "What makes climate action credible at an organisational level?", "Sustainability", "Hard", [60, 90]), make("sustainability-consumer", "How should consumers and companies share responsibility for sustainable choices?", "Sustainability", "Medium", [30, 60]),
  make("abstract-change", "Change is the only constant.", "Abstract", "Medium", [30, 60]), make("abstract-failure", "Failure is useful only when we learn from it.", "Abstract", "Easy", [30, 60]), make("abstract-simple", "Simplicity is a competitive advantage.", "Abstract", "Medium", [30, 60]), make("abstract-time", "The way we spend time reveals what we value.", "Abstract", "Easy", [30, 60]), make("abstract-risk", "Calculated risk is essential for progress.", "Abstract", "Medium", [60, 90]), make("abstract-listen", "Listening is an underestimated leadership skill.", "Abstract", "Easy", [30, 60]),
];

const blocked = /\b(war|attack|killed|arrest|murder|shooting|bomb|missile|election|politic|corruption|scam|death|crime)\b/i;
const entityDecode = (value: string) => value.replace(/<!\[CDATA\[|\]\]>/g, "").replace(/&amp;/g, "&").replace(/&quot;/g, "\"").replace(/&#39;/g, "'").replace(/<[^>]*>/g, "").trim();
const tag = (item: string, name: string) => entityDecode(item.match(new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`, "i"))?.[1] || "");
let trendCache: { expiresAt: number; topics: Topic[] } | null = null;
export function resetTrendCacheForTests() { trendCache = null; }

function categoryFor(title: string): Exclude<TopicCategory, "Random"> { if (/ai|software|computer|microsoft|apple|digital|tech/i.test(title)) return "Technology"; if (/market|company|business|startup|economy|shareholder/i.test(title)) return "Business"; if (/school|college|student|exam|education/i.test(title)) return "Education"; if (/job|work|career|employment/i.test(title)) return "Career"; return "Current Affairs"; }
export function getRandomTopic(category: TopicCategory = "Random", difficulty?: Difficulty, durationSeconds = 60): Topic { const eligible = topicCatalogue.filter(topic => (category === "Random" || topic.category === category) && (!difficulty || topic.difficulty === difficulty) && topic.suitableDurations.includes(durationSeconds as 30 | 60 | 90)); const source = eligible.length ? eligible : topicCatalogue.filter(topic => topic.suitableDurations.includes(durationSeconds as 30 | 60 | 90)); return { ...source[Math.floor(Math.random() * source.length)]!, durationSeconds, source: "curated", sourceLabel: "Curated practice prompt" }; }
export async function getCurrentTrendTopic(durationSeconds = 60): Promise<Topic> { if (trendCache && trendCache.expiresAt > Date.now() && trendCache.topics.length) return { ...trendCache.topics[Math.floor(Math.random() * trendCache.topics.length)]!, durationSeconds }; try { const response = await fetch("https://news.google.com/rss/search?q=technology+business+careers+education+innovation&hl=en-IN&gl=IN&ceid=IN:en", { signal: AbortSignal.timeout(4500), headers: { "user-agent": "SpeakUpTopicGenerator/1.0" } }); if (!response.ok) throw new Error("News feed unavailable"); const xml = await response.text(); const topics = xml.split(/<item>/i).slice(1).map((item, index) => ({ title: tag(item, "title"), publishedAt: tag(item, "pubDate") })).filter(item => item.title.length > 18 && item.title.length < 220 && !blocked.test(item.title)).slice(0, 16).map((item, index): Topic => ({ id: `trend-${Date.now()}-${index}`, text: `A current headline highlights: “${item.title}”. What opportunity, risk, or trade-off should leaders consider?`, category: categoryFor(item.title), difficulty: "Hard", suitableDurations: [60, 90], durationSeconds, source: "current", sourceLabel: "Current trend · Google News", publishedAt: item.publishedAt })); if (!topics.length) throw new Error("No suitable trends"); trendCache = { topics, expiresAt: Date.now() + 15 * 60 * 1000 }; return { ...topics[Math.floor(Math.random() * topics.length)]! }; } catch { const fallback = getRandomTopic("Current Affairs", undefined, durationSeconds); return { ...fallback, source: "curated", sourceLabel: "Curated fallback · current feed unavailable" }; } }
export async function getPracticeTopic(source: TopicSource, category: TopicCategory, difficulty: Difficulty | undefined, durationSeconds: 30 | 60 | 90) { return source === "current" ? getCurrentTrendTopic(durationSeconds) : getRandomTopic(category, difficulty, durationSeconds); }
