import { Button } from "@/components/ui/button";
import type { PracticeAnalysis } from "@shared/practice";
import { AlertCircle, CheckCircle2, Clipboard, Gauge, PauseCircle, PlayCircle, RotateCcw, Sparkles } from "lucide-react";
import { useRef, useState } from "react";

function highlightTranscript(transcript: string, fillers: string[]) {
  if (!transcript) return <span className="text-muted-foreground">Your transcript will appear here after you submit the recording for analysis.</span>;
  const matcher = fillers.length ? new RegExp(`(${fillers.map(word => word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})`, "gi") : null;
  if (!matcher) return transcript;
  return transcript.split(matcher).map((part, index) => fillers.some(word => word.toLowerCase() === part.toLowerCase()) ? <mark key={index}>{part}</mark> : part);
}

export function RecordingReview({ recordingUrl, analysis, transcript, isWorking, onAnalyze, onTryAgain }: { recordingUrl: string | null; analysis: PracticeAnalysis | null; transcript: string; isWorking: boolean; onAnalyze: () => void; onTryAgain: () => void }) {
  const [speed, setSpeed] = useState("1");
  const audioRef = useRef<HTMLAudioElement>(null);
  const audio = recordingUrl ? <audio ref={audioRef} className="w-full" controls src={recordingUrl} /> : null;
  return <div className="grid gap-5 lg:grid-cols-[.87fr_1.13fr]"><section className="review-card"><p className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Your recording</p><h2 className="mt-4 text-2xl font-semibold tracking-[-.04em]">Hear your delivery back.</h2><div className="mt-7 rounded-2xl border border-border bg-muted/50 p-4">{audio || <div className="flex h-14 items-center text-sm text-muted-foreground">Recording is being prepared…</div>}<div className="mt-3 flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-muted-foreground"><PlayCircle className="h-4 w-4" /> Playback speed</span><select aria-label="Playback speed" value={speed} onChange={event => { setSpeed(event.target.value); if (audioRef.current) audioRef.current.playbackRate = Number(event.target.value); }} className="rounded-lg border border-border bg-background px-2 py-1 text-xs font-medium"><option value="0.75">0.75×</option><option value="1">1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option></select></div></div><div className="mt-6 rounded-2xl bg-slate-950 p-5 text-white dark:bg-white dark:text-slate-950"><p className="text-xs font-semibold uppercase tracking-[.16em] opacity-55">Next step</p><p className="mt-2 text-lg font-semibold tracking-[-.035em]">{analysis ? "Use one improvement in your next attempt." : "Turn this recording into useful feedback."}</p>{analysis ? <Button onClick={onTryAgain} className="mt-5 rounded-full bg-[var(--accent)] text-white hover:bg-[var(--accent)]/90">Try another topic <RotateCcw className="ml-1 h-4 w-4" /></Button> : <Button disabled={isWorking} onClick={onAnalyze} className="mt-5 rounded-full bg-[var(--accent)] text-white hover:bg-[var(--accent)]/90">{isWorking ? "Analyzing your response…" : "Submit for feedback"} <Sparkles className="ml-1 h-4 w-4" /></Button>}</div></section>
    <section className="review-card">{analysis ? <><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]" /> Session insight</p><h2 className="mt-4 text-2xl font-semibold tracking-[-.04em]">Overall score <span className="font-serif italic text-[var(--accent)]">{analysis.overallScore}/100</span></h2></div><div className="rounded-2xl bg-[var(--soft-accent)] px-4 py-3 text-sm font-semibold text-[var(--accent-ink)]"><Gauge className="mr-2 inline h-4 w-4" />{analysis.wordsPerMinute} WPM</div></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-5">{Object.entries(analysis.scores).map(([label, score]) => <div key={label} className="score-pod"><span className="text-2xl font-semibold tracking-[-.06em]">{score}</span><span>{label}</span><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><span className="block h-full rounded-full bg-[var(--accent)]" style={{ width: `${score}%` }} /></div></div>)}</div><div className="mt-7 grid gap-3 md:grid-cols-2"><div className="feedback-box"><CheckCircle2 className="h-4 w-4 text-emerald-600" /><div><p className="font-semibold">What you did well</p>{analysis.strengths.map(point => <p key={point} className="mt-2 text-sm leading-6 text-muted-foreground">{point}</p>)}</div></div><div className="feedback-box"><AlertCircle className="h-4 w-4 text-[var(--accent)]" /><div><p className="font-semibold">Improve next</p>{analysis.improvements.map(point => <p key={point} className="mt-2 text-sm leading-6 text-muted-foreground">{point}</p>)}</div></div></div><div className="mt-5 rounded-2xl border border-border bg-muted/35 p-5"><p className="text-sm font-semibold">Suggested better structure</p><p className="mt-2 font-serif text-xl italic text-[var(--accent)]">{analysis.suggestedStructure}</p></div><div className="mt-5 rounded-2xl border border-border p-5"><div className="flex items-center justify-between"><p className="text-sm font-semibold">Speech transcript</p><Button variant="ghost" size="sm" onClick={() => navigator.clipboard?.writeText(transcript)} className="h-8 gap-1.5 rounded-lg text-xs"><Clipboard className="h-3.5 w-3.5" /> Copy</Button></div><p className="transcript mt-4">{highlightTranscript(transcript, analysis.fillerWords)}</p></div></> : <div className="flex min-h-[360px] flex-col items-center justify-center text-center"><PauseCircle className="h-10 w-10 text-[var(--accent)]" /><h2 className="mt-5 text-2xl font-semibold tracking-[-.04em]">Your analysis will appear here.</h2><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">We’ll review the shape of your answer, not just the number of seconds you spoke.</p></div>}</section></div>;
}
